version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install uv
      - uv pip install --system -r docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt