site_name: cccy
site_description: Python complexity measurement tool
site_url: !ENV [READTHEDOCS_CANONICAL_URL, "https://cccy.readthedocs.io/"]
repo_url: https://github.com/mmocchi/cccy
repo_name: mmocchi/cccy

theme:
  name: material
  language: ja
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: ja

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - ホーム: index.md
  - インストール: installation.md
  - 基本的な使い方: usage.md
  - コマンドリファレンス:
    - cccy check: commands/check.md
    - cccy show-list: commands/show-list.md
    - cccy show-summary: commands/show-summary.md
    - 設定ファイル: commands/configuration.md
  - 実用例: examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mmocchi/cccy