version: '3'

tasks:
  install:
    desc: Install dependencies with uv
    cmds:
      - uv sync --dev
  
  test:
    desc: Run tests
    cmds:
      - uv run pytest
  
  lint:
    desc: Run linting and type checking
    cmds:
      - uv run ruff check
      - uv run mypy src/
      - uv run mypy tests/
  
  format:
    desc: Format code
    cmds:
      - uv run ruff format
  
  format-check:
    desc: Check code formatting
    cmds:
      - uv run ruff format --check
  
  complexity:
    desc: Analyze code complexity
    cmds:
      - uv run cccy show-list src/
  
  complexity-summary:
    desc: Show complexity summary
    cmds:
      - uv run cccy show-summary src/
  
  complexity-check:
    desc: "Check complexity thresholds"
    cmds:
      - uv run cccy check --max-complexity 8 --max-cognitive 8 src/
      - uv run cccy check --max-complexity 6 --max-cognitive 6 tests/ --exclude "tests/application/services/fixtures/*" --exclude "tests/domain/services/fixtures/*" --exclude "tests/presentation/cli/fixtures/*"
  
  lint-imports:
    desc: Check import dependencies with import-linter
    cmds:
      - uv run lint-imports

  check:
    desc: Run all checks (complexity, linting, formatting, imports)
    cmds:
      - task: lint
      - task: format-check
      - task: test
      - task: complexity-check
      - task: lint-imports
  
  build:
    desc: Build package
    cmds:
      - uv build
  
  dev:
    desc: Install in development mode
    cmds:
      - uv pip install -e .
  
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/ build/ *.egg-info/
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
  
  tox:
    desc: Run tox for all Python versions
    cmds:
      - uv run tox
  
  tox-py39:
    desc: Run tox for Python 3.9
    cmds:
      - uv run tox -e py39
  
  tox-py310:
    desc: Run tox for Python 3.10
    cmds:
      - uv run tox -e py310
  
  tox-py311:
    desc: Run tox for Python 3.11
    cmds:
      - uv run tox -e py311
  
  tox-py312:
    desc: Run tox for Python 3.12
    cmds:
      - uv run tox -e py312
  
  tox-py313:
    desc: Run tox for Python 3.13
    cmds:
      - uv run tox -e py313
  
  tox-lint:
    desc: Run tox lint environment
    cmds:
      - uv run tox -e lint
  
  tox-test:
    desc: Run tox test environment
    cmds:
      - uv run tox -e test
  
  tox-complexity:
    desc: Run tox complexity environment
    cmds:
      - uv run tox -e complexity

  docs:serve:
    desc: Start MkDocs development server
    cmds:
      - pip install -r docs/requirements.txt
      - mkdocs serve

  docs:build:
    desc: Build MkDocs documentation
    cmds:
      - pip install -r docs/requirements.txt
      - mkdocs build