name: Auto Retry on Failure

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

permissions:
  actions: write
  contents: read

jobs:
  auto-retry:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Auto retry failed jobs
        uses: ./.github/actions/auto-retry-failed-jobs
        with:
          workflow_config: |
            Test:
              branches:
                - main
              jobs:
                - test
              max_retries: 2
          github_token: ${{ secrets.GITHUB_TOKEN }}